# Generated by Django 4.2.7 on 2023-11-28 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("circles", "0003_invitation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                (
                    "available_seats",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of available seats on the ride",
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("departure_location", models.CharField(max_length=255)),
                ("departure_date", models.DateTimeField()),
                ("arrival_location", models.CharField(max_length=255)),
                ("arrival_date", models.DateTimeField()),
                (
                    "rating",
                    models.FloatField(
                        default=0.0, help_text="Ride rating", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Used for disabling the ride or marking it as finished",
                        verbose_name="active status",
                    ),
                ),
                (
                    "offered_by",
                    models.ForeignKey(
                        help_text="Ride offered by user",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offered_rides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "offered_in",
                    models.ForeignKey(
                        help_text="Circle in which the ride is offered",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offered_rides",
                        to="circles.circle",
                    ),
                ),
                (
                    "passengers",
                    models.ManyToManyField(
                        help_text="Passengers that have joined the ride",
                        related_name="passenger_rides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created", "-modified"],
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
    ]
