# Generated by Django 4.2.7 on 2023-12-01 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("circles", "0003_invitation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rides", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Ride rating"
                    ),
                ),
                (
                    "circle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="circles.circle",
                    ),
                ),
                (
                    "rated_user",
                    models.ForeignKey(
                        help_text="User that receives the rating",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rated_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rating_user",
                    models.ForeignKey(
                        help_text="User that emits the rating",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rating_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ride",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rated_ride",
                        to="rides.ride",
                    ),
                ),
            ],
            options={
                "ordering": ["-created", "-modified"],
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
    ]
