# Generated by Django 4.2.7 on 2023-12-01 11:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rides", "0002_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="available_seats",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="Number of available seats on the ride"
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="passengers",
            field=models.ManyToManyField(
                help_text="Passengers that have joined the ride",
                related_name="passengers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="rating",
            field=models.FloatField(help_text="Ride rating", null=True),
        ),
    ]
