# Generated by Django 4.2.7 on 2023-11-20 09:06

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "get_latest_by": "created",
                "ordering": ["-created", "-modified"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Date time on which the object was created.",
                verbose_name="created at",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_client",
            field=models.BooleanField(
                default=True,
                help_text="Help easily distinguish users and perform queries.Clients are the main type of user.",
                verbose_name="client status",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="modified",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Date time on which the object was last modified.",
                verbose_name="modified at",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'.Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
                verbose_name="Phone number",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number_verified",
            field=models.BooleanField(
                default=False, verbose_name="Phone number verified"
            ),
        ),
    ]
