# Generated by Django 4.2.7 on 2023-11-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "users",
            "0002_alter_user_options_user_created_user_is_client_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="Set to true when the user have verified its email address.",
                verbose_name="verified",
            ),
        ),
    ]
