# Generated by Django 4.2.7 on 2023-12-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="biography",
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
