"""Circle invitation models."""

# Django
from django.db import models

# Managers
from c_ride.circles.managers import InvitationManager

# Utilities
from c_ride.utils.models import CRideModel


class Invitation(CRideModel):
    """Circle invitation


    A circle invitation is a random text that acts as
    a unique code that grants access to a specific circle.
    This codes are generated by users that are already
    members of the circle and have a `remaining_invitations`
    value greater than 0.
    """

    code = models.CharField(max_length=50, unique=True)

    issued_by = models.ForeignKey(
        "users.User",
        on_delete=models.CASCADE,
        help_text="Circle member that is providing the invitation",
        related_name="issued_by",
    )

    used_by = models.ForeignKey(
        "users.User",
        on_delete=models.CASCADE,
        null=True,
        help_text="User that used the code to enter the circle",
        related_name="used_by",
    )

    circle = models.ForeignKey("circles.Circle", on_delete=models.CASCADE)

    used = models.BooleanField(default=False)

    used_at = models.DateTimeField(blank=True, null=True)

    created_at = models.DateTimeField(
        "invitation created at",
        auto_now_add=True,
        help_text="Date time on which the invitation was created.",
    )

    # Managers
    objects = InvitationManager()

    def __str__(self):
        """Return code and circle."""
        return f"#{self.circle.slug_name}: {self.code}"
